-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPR CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@120",
	position = "0x0",
	scale = "auto",
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "prefered",
	position = "auto",
	scale = "auto",
})

-- monitor = HDMI-A-1,1920x1080@75, auto, auto

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "ghostty"

local fileManager = "nemo"

local menu = "wofi --show drun"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:

-- exec-once = $terminal

-- exec-once = nm-applet &

-- exec-once = hyprlock

-- exec-once = waybar & dunst & hyprpaper & hypridle &

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 16)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("GTK_THEME", "Juno:dark")

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 0,
		-- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
		-- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
		-- Set to true enable resizing windows by clicking and dragging on borders and gaps
		resize_on_border = false,
		-- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
		allow_tearing = false,
		layout = "dwindle",
		col = {
			active_border = "rgba(ffcc66bb)",
			inactive_border = "rgba(595959aa)",
		},
	},
})

hl.config({
	debug = {
		disable_logs = false,
		enable_stdout_logs = true,
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
	decoration = {
		rounding = 10,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = true,
			size = 4,
			passes = 2,
			ignore_opacity = true,
			new_optimizations = true,
			--vibrancy = 0.1696
			--vibrancy = 0.25
			--layerrule = blur,waybar
			--layerrule = blur,wofi
		},
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
	animations = {
		enabled = false,
		-- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
	},
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
	dwindle = {
		preserve_split = true,
		-- You probably want this
		--no_gaps_when_only = 1
		force_split = 2,
	},
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
	master = {
		orientation = "left",
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
	misc = {
		force_default_wallpaper = 1,
		-- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true,
		-- If true disables the random hyprland logo / anime girl background. :(
	},
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	input = {
		kb_layout = "fr",
		kb_variant = "azerty",
		follow_mouse = 1,
		numlock_by_default = true,
		sensitivity = 0,
		-- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
	},
})

hl.config({
	opengl = {
		nvidia_anti_flicker = false,
	},
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

hl.bind(mainMod .. " + " .. "I", hl.dsp.exec_cmd("chromium"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.exec_cmd("code --ozone-platform=wayland --disable-gpu"))

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("ghostty"))

-- bind = $mainMod SHIFT, Return, exec, $terminal --working-directory "$(pwd)"

hl.bind(mainMod .. " + " .. "KP_Enter", hl.dsp.exec_cmd("ghostty"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("nemo"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("clipman pick -t wofi"))

hl.bind(mainMod .. " + " .. "space", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "R", hl.dsp.exec_cmd("killall waybar && waybar &"))

-- hyprshot

-- Screenshot a window

hl.bind("SHIFT" .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m window --mode active -o ~/Images"))

-- Screenshot a monitor

hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m output --mode active -o ~/Images"))

-- Screenshot a region

hl.bind(mainMod .. " + " .. "PRINT", hl.dsp.exec_cmd("hyprshot -m region -o ~/Images"))

-- Brightness, volume and audio control

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute 0 toggle"))

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute 0 toggle"))

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +5%"))

hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -5%"))

hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd("brightnessctl set 10%+"))

hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd("brightnessctl set 10%-"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mainMod .. " + " .. "N", hl.dsp.exec_cmd("hyprctl hyprsunset temperature 2750"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "N", hl.dsp.exec_cmd("hyprctl hyprsunset identity"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "h", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "l", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + " .. "j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. "ampersand", hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "KP_End", hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "eacute", hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "KP_Down", hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "quotedbl", hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "KP_Next", hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "apostrophe", hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "KP_Left", hl.dsp.focus({ workspace = 4 }))

-- hl.bind(mainMod .. " + " .. "parentleft", hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "KP_Begin", hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "minus", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "KP_Right", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "egrave", hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "KP_Home", hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "underscore", hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "KP_Up", hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "ccedilla", hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "KP_Prior", hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "agrave", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "KP_Insert", hl.dsp.focus({ workspace = 10 }))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", { direction = "u" })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", { direction = "d" })

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ampersand", hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_End", hl.dsp.window.move({ workspace = 1 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "eacute", hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Down", hl.dsp.window.move({ workspace = 2 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "quotedbl", hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Next", hl.dsp.window.move({ workspace = 3 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "apostrophe", hl.dsp.window.move({ workspace = 4 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Left", hl.dsp.window.move({ workspace = 4 }, { follow = false }))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "parentleft", hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Begin", hl.dsp.window.move({ workspace = 5 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "minus", hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Right", hl.dsp.window.move({ workspace = 6 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "egrave", hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Home", hl.dsp.window.move({ workspace = 7 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "underscore", hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Up", hl.dsp.window.move({ workspace = 8 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "ccedilla", hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Prior", hl.dsp.window.move({ workspace = 9 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "agrave", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "KP_Insert", hl.dsp.window.move({ workspace = 10 }, { follow = false }))

-- Example special workspace (scratchpad)

hl.bind(mainMod .. " + " .. "S", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.window.resize_active({ delta = { 100, 0 } }))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "H", hl.dsp.window.resize_active({ delta = { -100, 0 } }))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "K", hl.dsp.window.resize_active({ delta = { 0, -100 } }))

-- hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "J", hl.dsp.window.resize_active({ delta = { 0, 100 } }))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("hyprlock"))

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

hl.window_rule({
	name = "suppress-maximize-events",
	match = {
		class = ".*",
	},
	suppress_event = "maximize",
})

hl.window_rule({
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},
	no_focus = true,
})

-- Hyprland-run windowrule

hl.window_rule({
	name = "move-hyprland-run",
	match = {
		class = "hyprland-run",
	},
	move = { 20, "monitor_h-120" },
	float = true,
})

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("awww daemon & wayle panel start & wayle wallpaper next & hypridle & hyprsunset &")
	hl.exec_cmd("wl-paste -t text --watch clipman store --no-persist")
end)
